# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('git_username', models.CharField(max_length=45)),
                ('default_password', models.CharField(max_length=45)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('language_code', models.CharField(max_length=2)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lines_count', models.IntegerField(null=True)),
                ('initial_segment_count', models.IntegerField(null=True)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('deadline_datetime', models.DateTimeField(null=True)),
                ('media_filename', models.CharField(max_length=255)),
                ('transcript_filename', models.CharField(max_length=255)),
                ('source_directory_path', models.CharField(max_length=255)),
                ('is_allocated', models.BooleanField(default=False)),
                ('is_declared_finished', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('latest_comment', models.TextField(default='')),
                ('progress', models.FloatField(default=0.0)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mdls.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('marker_count', models.IntegerField()),
                ('segment_count', models.IntegerField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdls.Editor')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdls.File')),
            ],
        ),
    ]
