# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='default_password',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='git_username',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
