# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0002_auto_20160308_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='default_password',
            new_name='default_git_password',
        ),
    ]
