# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0003_auto_20160308_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='default_git_password',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='git_username',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
