# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0004_auto_20160308_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='deadline_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdls.Editor'),
        ),
        migrations.AlterField(
            model_name='file',
            name='initial_segment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='total_lines_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
