# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0008_remove_file_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='http_git_repo',
            field=models.TextField(default='', max_length=2083),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editor',
            name='ssh_git_repo',
            field=models.TextField(default=' ', max_length=2083),
            preserve_default=False,
        ),
    ]
