# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0009_auto_20160309_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='default_git_password',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='git_username',
        ),
    ]
