# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0011_auto_20160309_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('creation', 'Creation'), ('correction', 'Correction')], default='correction', max_length=25),
        ),
    ]
