# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0012_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='initial_segment_count',
        ),
        migrations.RemoveField(
            model_name='file',
            name='total_lines_count',
        ),
    ]
